#include <iostream>

#include "Application.h"


// THE SPHERE DOESN'T WORK BECAUSE IN DISPLAYCB FUNCTION THE VALUES ARE COMPLETELY OFF.
// OBJMGR TO SWITCH WHAT LOADS, EVERYTHING BESIDES SPHERE CURRENTLY WORKING 5 - 19 - 2024
// LEFT CTRL TO WIREFRAME TOGGLE IS A BIT BROKEN, NEEDS TO BE TIMED OUT SO IT DOESN'T SWITCH ON AND OFF RLY FAST
// GLUT IS NOT USED, EVEN THOUGH IT IS IN THE DEPENDENCIES

int main()
{
	Application app;

	app.Start();

	return 0;
}