#include "Application.h"

// TODO:
// CREATE FUNCTIONS IN GUI LIKE CREATECHECKBOX THAT ALLOW YOU TO INPUT STRING AND BOOLEAN TO CREATE GUI ELEMENTS
// DECIDE IF YOU WANT TO MAKE A SHOULD_RENDER IN IMGUI TO TOGGLE BODIES (THIS WOULD STRAY AWAY FROM THREEBODYSIM)

int main()
{
	Application app;

	app.Start();

	return 0;
}